package com.enaboapps.switchify.nav

sealed class NavigationRoute(val name: String) {

    data object Home : NavigationRoute("Home")
    data object Setup : NavigationRoute("Setup")
    data object Paywall : NavigationRoute("Paywall")
    data object SignIn : NavigationRoute("SignIn")
    data object SignUp : NavigationRoute("SignUp")
    data object ForgotPassword : NavigationRoute("ForgotPassword")
    data object Account : NavigationRoute("Account")
    data object ChangePassword : NavigationRoute("ChangePassword")
    data object Settings : NavigationRoute("Settings")
    data object SwitchStability : NavigationRoute("SwitchStability")
    data object ScanColor : NavigationRoute("ScanColor")
    data object CursorSettings : NavigationRoute("CursorSettings")
    data object ItemScanSettings : NavigationRoute("ItemScanSettings")
    data object OtherScanSettings : NavigationRoute("OtherScanSettings")
    data object RadarSettings : NavigationRoute("RadarSettings")
    data object Switches : NavigationRoute("Switches")
    data object AddNewExternalSwitch : NavigationRoute("AddNewExternalSwitch")
    data object EditExternalSwitch : NavigationRoute("EditExternalSwitch")
    data object TestSwitches : NavigationRoute("TestSwitches")
    data object MenuItemCustomization : NavigationRoute("MenuItemCustomization")
    data object MenuSize : NavigationRoute("MenuSize")
    data object MyActions : NavigationRoute("MyActions")
    data object AddMyActionsMenuItem : NavigationRoute("AddMyActionsMenuItem")
    data object EditMyActionsMenuItem : NavigationRoute("EditMyActionsMenuItem")
    data object EnableAccessibilityService : NavigationRoute("EnableAccessibilityService")
    data object AddNewCameraSwitch : NavigationRoute("AddNewCameraSwitch")
    data object EditCameraSwitch : NavigationRoute("EditCameraSwitch")
    data object Debug : NavigationRoute("Debug")
}
