package com.enaboapps.switchify.nav

sealed class NavigationRoute(val name: String) {

    data object Home : NavigationRoute("Home")
    data object Onboarding : NavigationRoute("Onboarding")
    data object Paywall : NavigationRoute("Paywall")
    data object Authentication : NavigationRoute("Authentication")
    data object Account : NavigationRoute("Account")
    data object Settings : NavigationRoute("Settings")
    data object SwitchStability : NavigationRoute("SwitchStability")
    data object GestureSettings : NavigationRoute("GestureSettings")
    data object ScanSpeeds : NavigationRoute("ScanSpeeds")
    data object ManualScanSettings : NavigationRoute("ManualScanSettings")
    data object ScanColor : NavigationRoute("ScanColor")
    data object AutoScanSettings : NavigationRoute("AutoScanSettings")
    data object AccessTechniqueSettings : NavigationRoute("AccessTechniqueSettings")
    data object Switches : NavigationRoute("Switches")
    data object ExternalSwitches : NavigationRoute("ExternalSwitches")
    data object CameraSwitches : NavigationRoute("CameraSwitches")
    data object AddNewExternalSwitch : NavigationRoute("AddNewExternalSwitch")
    data object EditExternalSwitch : NavigationRoute("EditExternalSwitch")
    data object EnableAccessibilityService : NavigationRoute("EnableAccessibilityService")
    data object AddNewCameraSwitch : NavigationRoute("AddNewCameraSwitch")
    data object EditCameraSwitch : NavigationRoute("EditCameraSwitch")
    data object Debug : NavigationRoute("Debug")
    data object GesturePatterns : NavigationRoute("GesturePatterns")
    data object UsageStatsPermission : NavigationRoute("UsageStatsPermission")
    data object UserFeedback : NavigationRoute("UserFeedback")
    data object CameraSettings : NavigationRoute("CameraSettings")
    data object HeadControlSettings : NavigationRoute("HeadControlSettings")
    data object PauseSettings : NavigationRoute("PauseSettings")
    data object MenuCustomization : NavigationRoute("MenuCustomization")
}
